'''
Largest prime factor
Problem 3

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

import math
a = 0
n = 600851475143
def is_prime(k):
    for i in range(2,int(math.sqrt(k))+1):
        if (k%i) == 0:
            return False
    return True
for i in range(1,int(math.sqrt(n))):
    if (n%i) == 0 and is_prime(i):
        a = i
print(a)

#answer : 6857
